#!/usr/bin/env bash
# Minimal install for a machine that only needs `floodsd` ("flood standalone")
# — the standalone remote load-generator. Installs nothing else: no themes,
# oh-my-zsh, nvim config, tmux config, kitty/iterm2 config, or shell rc
# changes. Safe to hand to someone else's box.
#
# `floodsd` is a deliberately different name from `floodfd` (the zsh function
# in zsh/firedancer-flood.zsh, used by the full dotfiles install) so the two
# can coexist on the same machine without colliding — same behavior, separate
# binary/state/temp files, no zsh dependency, works from bash or zsh on any
# distro.
#
# What this does:
#   - Copies bin/floodsd (a single self-contained bash script) to
#     ~/.local/bin — never system-wide. This typically runs on someone
#     else's server (you have sudo, but it's their box), so nothing gets
#     installed outside your own user dir except the specific kernel/NIC
#     operations (vfio-pci bind, hugepages, pktgen module) that floodsd
#     itself needs sudo for at runtime — those are unavoidably system state,
#     not files left behind.
#
# That's the whole install. DPDK/Pktgen-DPDK, if you use `floodsd dpdk`, is
# installed lazily on first run with its own confirmation prompt. DPDK's own
# dev packages come from the system package manager (no user-dir equivalent
# without rebuilding DPDK from source), but Pktgen-DPDK itself is built and
# installed into ~/.local — this script never touches /usr/local or system
# package state up front.
#
# Run on the server:  bash install-floodsd.sh

set -uo pipefail
DOTFILES_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SRC="$DOTFILES_DIR/bin/floodsd"

if [ ! -f "$SRC" ]; then
    echo "[ERROR] $SRC not found — is this script running from inside a clone of the dotfiles repo?"
    exit 1
fi

dest_dir="$HOME/.local/bin"
mkdir -p "$dest_dir"
cp "$SRC" "$dest_dir/floodsd"
chmod +x "$dest_dir/floodsd"
echo "[floodsd] Installed to $dest_dir/floodsd."

# updateflood: refresh floodsd only (re-fetch this repo, re-run this installer).
# The parallel to updatedot, but floodsd-only: installs nothing new and makes no
# shell/rc changes. Dropped into ~/.local/bin (same user dir as floodsd) so it
# works from bash or zsh with no dotfiles dependency. $DOTFILES_DIR is baked in
# at install time so it works even if this repo isn't at ~/dotfiles.
cat > "$dest_dir/updateflood" <<'UPDATEFLOOD'
#!/usr/bin/env bash
# Auto-generated by install-floodsd.sh. Refreshes ONLY floodsd -- installs
# nothing new, makes no shell/rc changes. The floodsd parallel to updatedot.
set -uo pipefail
REPO_DIR="__DOTFILES_DIR__"
[ -d "$REPO_DIR/.git" ] || REPO_DIR="$HOME/dotfiles"
if [ ! -d "$REPO_DIR/.git" ]; then
    echo "[updateflood] dotfiles repo not found at $REPO_DIR -- clone it first." >&2
    exit 1
fi
cd "$REPO_DIR" || exit 1
echo "[updateflood] Fetching latest from $REPO_DIR..."
git fetch && git reset --hard origin/main || {
    echo "[updateflood] git update failed." >&2; exit 1; }
exec bash "$REPO_DIR/install-floodsd.sh"
UPDATEFLOOD
# Bake the resolved repo path in (the heredoc above is quoted, so $DOTFILES_DIR
# is a literal placeholder until now).
sed -i "s|__DOTFILES_DIR__|$DOTFILES_DIR|" "$dest_dir/updateflood"
chmod +x "$dest_dir/updateflood"
echo "[floodsd] updateflood installed to $dest_dir/updateflood (refreshes floodsd only)."
case ":$PATH:" in
    *":$dest_dir:"*) echo "[floodsd] $dest_dir is on your PATH — run: floodsd setup" ;;
    *) echo "[floodsd] $dest_dir isn't on your PATH — run it directly: $dest_dir/floodsd setup" ;;
esac
