#!/usr/bin/env bash
# Minimal install for a machine that only needs `floodsd` ("flood standalone")
# — the standalone remote load-generator. Installs nothing else: no themes,
# oh-my-zsh, nvim config, tmux config, kitty/iterm2 config, or shell rc
# changes. Safe to hand to someone else's box.
#
# `floodsd` is a deliberately different name from `floodfd` (the zsh function
# in zsh/firedancer-flood.zsh, used by the full dotfiles install) so the two
# can coexist on the same machine without colliding — same behavior, separate
# binary/state/temp files, no zsh dependency, works from bash or zsh on any
# distro.
#
# What this does:
#   - Copies bin/floodsd (a single self-contained bash script) to
#     ~/.local/bin — never system-wide. This typically runs on someone
#     else's server (you have sudo, but it's their box), so nothing gets
#     installed outside your own user dir except the specific kernel/NIC
#     operations (vfio-pci bind, hugepages, pktgen module) that floodsd
#     itself needs sudo for at runtime — those are unavoidably system state,
#     not files left behind.
#
# That's the whole install. DPDK/Pktgen-DPDK, if you use `floodsd dpdk`, is
# installed lazily on first run with its own confirmation prompt. DPDK's own
# dev packages come from the system package manager (no user-dir equivalent
# without rebuilding DPDK from source), but Pktgen-DPDK itself is built and
# installed into ~/.local — this script never touches /usr/local or system
# package state up front.
#
# Run on the server:  bash install-floodsd.sh

set -uo pipefail
DOTFILES_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SRC="$DOTFILES_DIR/bin/floodsd"

if [ ! -f "$SRC" ]; then
    echo "[ERROR] $SRC not found — is this script running from inside a clone of the dotfiles repo?"
    exit 1
fi

dest_dir="$HOME/.local/bin"
mkdir -p "$dest_dir"
cp "$SRC" "$dest_dir/floodsd"
chmod +x "$dest_dir/floodsd"
echo "[floodsd] Installed to $dest_dir/floodsd."

# updateflood: refresh floodsd only (re-fetch this repo, re-run this installer).
# The parallel to updatedot, but floodsd-only: installs nothing new and makes no
# shell/rc changes. Dropped into ~/.local/bin (same user dir as floodsd) so it
# works from bash or zsh with no dotfiles dependency. $DOTFILES_DIR is baked in
# at install time so it works even if this repo isn't at ~/dotfiles.
cat > "$dest_dir/updateflood" <<'UPDATEFLOOD'
#!/usr/bin/env bash
# Auto-generated by install-floodsd.sh. Refreshes ONLY floodsd -- installs
# nothing new, makes no shell/rc changes. The floodsd parallel to updatedot.
set -uo pipefail
REPO_DIR="__DOTFILES_DIR__"
[ -d "$REPO_DIR/.git" ] || REPO_DIR="$HOME/dotfiles"
if [ ! -d "$REPO_DIR/.git" ]; then
    echo "[updateflood] dotfiles repo not found at $REPO_DIR -- clone it first." >&2
    exit 1
fi
cd "$REPO_DIR" || exit 1
echo "[updateflood] Fetching latest from $REPO_DIR..."
git fetch && git reset --hard origin/main || {
    echo "[updateflood] git update failed." >&2; exit 1; }
exec bash "$REPO_DIR/install-floodsd.sh"
UPDATEFLOOD
# Bake the resolved repo path in (the heredoc above is quoted, so $DOTFILES_DIR
# is a literal placeholder until now).
sed -i "s|__DOTFILES_DIR__|$DOTFILES_DIR|" "$dest_dir/updateflood"
chmod +x "$dest_dir/updateflood"
echo "[floodsd] updateflood installed to $dest_dir/updateflood (refreshes floodsd only)."
# Make floodsd/updateflood usable by name. If ~/.local/bin is already on PATH
# (common on many distros), nothing to do. Otherwise offer -- opt-in only, never
# silently -- to add it to the shell rc, preserving this installer's "safe on
# someone else's box, no surprise rc edits" promise. Declining prints the
# run-directly hint. A non-interactive run (no TTY) never edits anything.
case ":$PATH:" in
    *":$dest_dir:"*)
        echo "[floodsd] $dest_dir is on your PATH -- run: floodsd setup"
        ;;
    *)
        # Pick the rc for the current login shell.
        case "$(basename "${SHELL:-}")" in
            zsh)  rc="$HOME/.zshrc" ;;
            bash) rc="$HOME/.bashrc" ;;
            *)    rc="$HOME/.profile" ;;
        esac
        add_path=""
        if [ -t 0 ]; then
            printf "[floodsd] %s isn't on your PATH. Add it to %s? [y/N] " "$dest_dir" "$rc"
            read -r reply
            case "$reply" in [yY]|[yY][eE][sS]) add_path=1 ;; esac
        fi
        if [ -n "$add_path" ]; then
            # Idempotent: only append if we haven't already added this line.
            marker="# added by install-floodsd.sh: put ~/.local/bin on PATH"
            if ! grep -qsF "$marker" "$rc"; then
                {
                    echo ""
                    echo "$marker"
                    echo 'case ":$PATH:" in *":$HOME/.local/bin:"*) ;; *) export PATH="$HOME/.local/bin:$PATH" ;; esac'
                } >> "$rc"
                echo "[floodsd] Added ~/.local/bin to PATH in $rc."
            else
                echo "[floodsd] $rc already has the PATH line."
            fi
            echo "[floodsd] Open a new shell (or: source $rc), then run: floodsd setup"
        else
            echo "[floodsd] $dest_dir isn't on your PATH -- run it directly: $dest_dir/floodsd setup"
        fi
        ;;
esac
